project:
  type: website
  output-dir: docs
website:
  title: "RC42"
  image: images/rc42logo-blue.PNG
  favicon: images/isa-favicon.png
  twitter-card:
    site: "@rwdatasci"
  open-graph: true
  # site-url: https://realworlddatascience.net/
  repo-url: https://github.com/isa-rc42/webRC42ISA
  repo-actions: [edit, issue]
  # If you are forking our repo to develop content -- whether for Real World Data Science
  # or your own purposes -- please disable our Google Analytics tag during development.
  # If building your own site, replace our GA tag with your own GA tag before deployment.
  # This will prevent your activity being tracked and counted in our analytics dashboard.
  # Thank you!
  google-analytics: "G-1TTWB7YTR6"
  navbar:
    toggle-position: right
    background: "#009fe3"
    logo: images/rc42logo-blue.png
    logo-alt: "RC42-ISA"
    title: false
    collapse-below: sm
    pinned: false
    right:
      - projects/projects.qmd
      - publications/publications.qmd
      - links/links.qmd
      - text: "About"
        menu:
        - text: "Board"
          href: board/index.qmd
        - text: "Members"
          href: members/index.qmd
        # - text: "Code of conduct"
        #   href: CODE_OF_CONDUCT.mds
        # - text: "Contact us"
        #   href: contact.qmd

  # sidebar:
  #   - title: "About us"
  #     contents:
  #       - about-isa42.qmd
        # - viewpoints/editors-blog/posts/2022/10/18/meet-the-team.qmd
        # - rwds-partners.qmd
        # - contact.qmd
        # - ts-and-cs.qmd
        # - CODE_OF_CONDUCT.md
        # - LICENCE.md
    # - title: "Call for contributions"
    #   contents:
    #     - contributor-docs/call-for-contributions.qmd
    #     - contributor-docs/case-studies.qmd
    #     - contributor-docs/explainers.qmd
    #     - contributor-docs/exercises.qmd
    #     - contributor-docs/datasets.qmd
    #     - contributor-docs/training-guides.qmd
    #     - contributor-docs/recommender.qmd
    #     - contributor-docs/datasciencebites.qmd
    #     - contributor-docs/contributor-guidelines.qmd
    #     - contributor-docs/style-guide.qmd
    # - title: "Careers"
    #   contents:
    #     - careers/index.qmd
    #     - careers/career-profiles/index.qmd
    # - title: "Ideas"
    #   contents:
    #     - ideas/index.qmd
    #     - ideas/tutorials/index.qmd
    #     - ideas/datasciencebites/index.qmd
    # - title: "Viewpoints"
    #   contents:
    #     - viewpoints/index.qmd
    #     - viewpoints/editors-blog/index.qmd
    #     - viewpoints/interviews/index.qmd
    #     - href: viewpoints/newsletter/index.qmd
    #       text: Newsletter

  page-navigation: true


  page-footer:
    background: "#000000"
    left: |
      [2024]()
    center:
      - href: https://github.com/isa-rc42/webRC42ISA
        icon: github
        aria-label: GitHub
      # - href: https://zenodo.org/communities/realworlddatascience
      #   text: "{{< ai zenodo size=2xl >}}"
      #   aria-label: RWDS Zenodo community
      # - href: https://www.linkedin.com/showcase/rss-real-world-data-science
      #   icon: linkedin
      #   aria-label: LinkedIn
      # - href: https://twitter.com/rwdatasci
      #   icon: twitter-x
      #   aria-label: Twitter/X
      # - href: https://fosstodon.org/@rwdatasci
      #   icon: mastodon
      #   aria-label: Mastodon
      # - href: feeds.html
      #   icon: rss
      #   aria-label: RWDS rss

    right: |
      [About RC42](https://www.isa-sociology.org/en/research-networks/research-committees/rc42-social-psychology)

format:
  html:
    theme: [lux, rwds.scss]
    css: rwds.css
    toc: true
    grid:
      sidebar-width: 0px
      body-width: 1000px
      margin-width: 250px

execute:
  freeze: auto
